"""update 

Revision ID: 9bbbed0f9b9f
Revises: 917c5c3ca20a
Create Date: 2023-09-14 18:38:46.420308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bbbed0f9b9f'
down_revision: Union[str, None] = '917c5c3ca20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_table', sa.Column('contract_table.customer.seller_contact_id', sa.Integer(), nullable=True))
    op.drop_constraint('contract_table_seller_id_fkey', 'contract_table', type_='foreignkey')
    op.drop_column('contract_table', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_table', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('contract_table_seller_id_fkey', 'contract_table', 'seller_table', ['seller_id'], ['id'])
    op.drop_column('contract_table', 'contract_table.customer.seller_contact_id')
    # ### end Alembic commands ###
