"""update seller_id_Contract 

Revision ID: 062533ce2c93
Revises: 9bbbed0f9b9f
Create Date: 2023-09-14 18:48:02.001751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062533ce2c93'
down_revision: Union[str, None] = '9bbbed0f9b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_table', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contract_table', 'seller_table', ['seller_id'], ['id'])
    op.drop_column('contract_table', 'contract_table.customer.seller_contact_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_table', sa.Column('contract_table.customer.seller_contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contract_table', type_='foreignkey')
    op.drop_column('contract_table', 'seller_id')
    # ### end Alembic commands ###
