"""replace Company table for attribut[str] in customer table

Revision ID: 4c9144a538f8
Revises: 2e7e0b35d72f
Create Date: 2023-09-08 10:58:19.045132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c9144a538f8"
down_revision: Union[str, None] = "2e7e0b35d72f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("customer_table_company_id_fkey", "customer_table", type_="foreignkey")
    op.drop_column("customer_table", "company_id")
    op.drop_table(
        "company_table",
    )
    op.add_column("customer_table", sa.Column("company", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customer_table", sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key("customer_table_company_id_fkey", "customer_table", "company_table", ["company_id"], ["id"])
    op.drop_column("customer_table", "company")
    op.create_table(
        "company_table",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("phone_number", sa.VARCHAR(length=12), autoincrement=False, nullable=True),
        sa.Column("number_of_employee", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("address_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["address_id"], ["address_table.id"], name="company_table_address_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="company_table_pkey"),
    )
    # ### end Alembic commands ###
