"""ondelete=CASCADE on USER class

Revision ID: 4f14d3bdde12
Revises: 876e958a8781
Create Date: 2023-09-13 17:46:15.996184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f14d3bdde12"
down_revision: Union[str, None] = "876e958a8781"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("manager_table_id_fkey", "manager_table", type_="foreignkey")
    op.create_foreign_key(None, "manager_table", "user_table", ["id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("seller_table_id_fkey", "seller_table", type_="foreignkey")
    op.create_foreign_key(None, "seller_table", "user_table", ["id"], ["id"], ondelete="CASCADE")
    op.drop_constraint("supporter_table_id_fkey", "supporter_table", type_="foreignkey")
    op.create_foreign_key(None, "supporter_table", "user_table", ["id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "supporter_table", type_="foreignkey")
    op.create_foreign_key("supporter_table_id_fkey", "supporter_table", "user_table", ["id"], ["id"])
    op.drop_constraint(None, "seller_table", type_="foreignkey")
    op.create_foreign_key("seller_table_id_fkey", "seller_table", "user_table", ["id"], ["id"])
    op.drop_constraint(None, "manager_table", type_="foreignkey")
    op.create_foreign_key("manager_table_id_fkey", "manager_table", "user_table", ["id"], ["id"])
    # ### end Alembic commands ###
